export const NIVEL_PACK = {
    "principal": {
        "matriz": [
            [
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14
            ],
            [
                14,
                0,
                0,
                0,
                5,
                5,
                0,
                14,
                21,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                3,
                0,
                5,
                5,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                5,
                5,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                19,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                19,
                14
            ],
            [
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14
            ]
        ],
        "enemigos": [
            {
                "type": "Generador Esqueletos",
                "tipo": "Generador Esqueletos",
                "gridX": 4,
                "gridY": 9,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "Generador Esqueletos",
                "tipo": "Generador Esqueletos",
                "gridX": 4,
                "gridY": 4,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 10
            }
        ],
        "portales": [
            {
                "gridX": 6,
                "gridY": 4,
                "etiqueta": "portal_principal_to_cueva_6_4",
                "destinoMapa": "cueva",
                "destinoPortal": "portal_cueva_to_principal_1_1"
            },
            {
                "gridX": 8,
                "gridY": 1,
                "etiqueta": "portal_principal_to_cueva_8_1",
                "destinoMapa": "cueva",
                "destinoPortal": "portal_cueva_to_principal_8_7"
            },
            {
                "gridX": 18,
                "gridY": 4,
                "etiqueta": "portal_principal_to_cueva_18_4",
                "destinoMapa": "cueva",
                "destinoPortal": "portal_cueva_to_principal_10_7"
            }
        ],
        "cofres": [],
        "cajas": [],
        "mecanismos": [],
        "holdouts": [
            {
                "gridX": 3,
                "gridY": 3,
                "radio": 4,
                "tiempo": 5,
                "penalidad": "LOSE_LEVEL"
            }
        ],
        "lasers": [],
        "espejos": [],
        "receptores": [],
        "secuencias": []
    },
    "cueva": {
        "matriz": [
            [
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14
            ],
            [
                14,
                21,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                19,
                14,
                21,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                14
            ],
            [
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14
            ]
        ],
        "enemigos": [
            {
                "type": "BAKU",
                "tipo": "BAKU",
                "gridX": 2,
                "gridY": 5,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 4,
                "spawnCount": 1
            },
            {
                "type": "BAKU",
                "tipo": "BAKU",
                "gridX": 5,
                "gridY": 5,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 4,
                "spawnCount": 1
            },
            {
                "type": "BAKU",
                "tipo": "BAKU",
                "gridX": 4,
                "gridY": 4,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 4,
                "spawnCount": 1
            },
            {
                "type": "EXPLOSIVE_SHOOTER",
                "tipo": "EXPLOSIVE_SHOOTER",
                "gridX": 14,
                "gridY": 6,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "EXPLOSIVE_SHOOTER",
                "tipo": "EXPLOSIVE_SHOOTER",
                "gridX": 12,
                "gridY": 5,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "EXPLOSIVE_SHOOTER",
                "tipo": "EXPLOSIVE_SHOOTER",
                "gridX": 15,
                "gridY": 5,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "EXPLOSIVE_SHOOTER",
                "tipo": "EXPLOSIVE_SHOOTER",
                "gridX": 13,
                "gridY": 4,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "EXPLOSIVE_SHOOTER",
                "tipo": "EXPLOSIVE_SHOOTER",
                "gridX": 11,
                "gridY": 4,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "SHOOTER_CHILD",
                "tipo": "SHOOTER_CHILD",
                "gridX": 3,
                "gridY": 13,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "SHOOTER_CHILD",
                "tipo": "SHOOTER_CHILD",
                "gridX": 3,
                "gridY": 14,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "SHOOTER_CHILD",
                "tipo": "SHOOTER_CHILD",
                "gridX": 5,
                "gridY": 15,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "SHOOTER_CHILD",
                "tipo": "SHOOTER_CHILD",
                "gridX": 5,
                "gridY": 14,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "SHOOTER_CHILD",
                "tipo": "SHOOTER_CHILD",
                "gridX": 6,
                "gridY": 14,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "SHOOTER_CHILD",
                "tipo": "SHOOTER_CHILD",
                "gridX": 6,
                "gridY": 15,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 1
            },
            {
                "type": "Generador Esqueletos",
                "tipo": "Generador Esqueletos",
                "gridX": 7,
                "gridY": 4,
                "vida": 70,
                "velocidad": 85,
                "defensa": 10,
                "resistencias": {},
                "decoradores": [],
                "danioBase": 2,
                "tipoDanio": "PORCENTAJE_BASE",
                "cantidad": 1,
                "spawnCount": 10
            }
        ],
        "portales": [
            {
                "gridX": 1,
                "gridY": 1,
                "etiqueta": "portal_cueva_to_principal_1_1",
                "destinoMapa": "principal",
                "destinoPortal": "portal_principal_to_cueva_6_4"
            },
            {
                "gridX": 8,
                "gridY": 7,
                "etiqueta": "portal_cueva_to_principal_8_7",
                "destinoMapa": "principal",
                "destinoPortal": "portal_principal_to_cueva_8_1"
            },
            {
                "gridX": 10,
                "gridY": 7,
                "etiqueta": "portal_cueva_to_principal_10_7",
                "destinoMapa": "principal",
                "destinoPortal": "portal_principal_to_cueva_18_4"
            }
        ],
        "cofres": [],
        "cajas": [],
        "mecanismos": [],
        "holdouts": [],
        "lasers": [],
        "espejos": [],
        "receptores": [],
        "secuencias": []
    }
};